#!/bin/bash

export MQTT_ID=""
export MQTT_HOST=""

# Remove the # symbol (uncomment) in the 2 lines below if 
# the server requires authentication

# export MQTT_USER=""
# export MQTT_PASS=""
export MQTT_TOPIC=""

sudo -E ./rf95_server
